"""VoltBox in the demo story: a quiet week, then its charging cases overheat (story/content.py)."""

from datetime import timedelta

from serpsense.adapters.replay.story.content import (
    OFF,
    REFUNDS,
    Article,
    Content,
    Query,
    Question,
    Result,
    Review,
    StoryBrand,
    Suggestion,
    Tag,
    bad,
    good,
    plain,
)
from serpsense.domain.enums import Topic

V = "https://voltbox.example.com"
VOLTBOX = Content(
    results=(
        Result(
            0,
            10,
            "VoltBox: wireless earbuds and fast chargers",
            "Official site. Shop the "
            "VoltBox Air 2, power banks and GaN chargers with free delivery across India.",
            f"{V}/",
            plain("The brand's own site."),
        ),
        Result(
            0,
            20,
            "VoltBox Air 2 review: big bass, bigger battery",
            "Nine hours a charge and "
            "three more in the case. At Rs 2,999 the Air 2 is hard to beat.",
            "https://reviews.example.com/voltbox-air-2",
            good("A warm review of the Air 2."),
        ),
        Result(
            0,
            30,
            "VoltBox Connect: the companion app",
            "Pair your VoltBox earbuds, update their firmware and tune the sound.",
            "https://apps.example.com/voltbox-connect",
            plain("The brand's app listing.", Topic.APP_EXPERIENCE),
        ),
        Result(
            0,
            40,
            "VoltBox vs SoundNest: the best budget earbuds of 2026",
            "We tested both for a month. VoltBox lasts longer, SoundNest fits better.",
            "https://gadgets.example.com/voltbox-vs-soundnest",
            plain("A fair comparison."),
        ),
        Result(
            16,
            15,
            "Charging case gets hot overnight: VoltBox Air 2 thread",
            "Mine was too hot to hold after an hour on the charger, and now the lid doesn't close.",
            "https://forum.example.com/t/voltbox-air-2-case-hot",
            bad(70, "A buyer's case overheated and deformed while charging."),
        ),
        Result(
            19,
            5,
            "Users report VoltBox earbuds overheating while charging",
            "Several owners of the Air 2 say the case got hot enough to warp.",
            "https://gadgetledger.example.com/news/voltbox-overheating",
            bad(80, "Reports of the case overheating, now covered by the press."),
        ),
        Result(
            19,
            25,
            "VoltBox Air 2 case swelling: photos inside",
            "The case bulges at the hinge after a few weeks of overnight charging.",
            "https://forum.example.com/t/voltbox-case-swelling",
            bad(75, "Photos of swollen charging cases."),
        ),
        Result(
            20,
            6,
            "Consumer forum flags swelling VoltBox charging cases",
            "Complaints about the Air 2's case have tripled in a week, the forum says.",
            "https://consumerwatch.example.com/voltbox-cases",
            bad(85, "A consumer group flags the swelling cases."),
        ),
        Result(
            20,
            7,
            "VoltBox Air 2 recall? What we know so far",
            "No recall yet, but owners are told to stop charging overnight.",
            "https://techledger.example.com/voltbox-recall-what-we-know",
            bad(75, "Talk of a recall over the cases."),
        ),
        Result(
            20,
            26,
            "Is my VoltBox case safe? A battery engineer explains",
            "Swelling is a sign the cell is failing: stop using it.",
            "https://reviews.example.com/voltbox-case-safe",
            bad(70, "An expert says to stop using swollen cases."),
        ),
    ),
    questions=(
        Question(0, 1, "Is VoltBox a good brand?", plain("A general question about the brand.")),
        Question(0, 2, "Are VoltBox Air 2 waterproof?", plain("A product question.")),
        Question(0, 3, "Where are VoltBox earbuds made?", plain("A product question.")),
        Question(
            18,
            0,
            "Why is my VoltBox charging case hot?",
            bad(55, "People search why the case heats up."),
        ),
        Question(
            19,
            0,
            "Is it safe to charge VoltBox earbuds overnight?",
            bad(65, "People ask whether overnight charging is safe."),
        ),
        Question(
            20,
            0,
            "Can a VoltBox charging case catch fire?",
            bad(80, "People ask whether the case can catch fire."),
        ),
    ),
    suggestions=(
        Suggestion(0, 1, "voltbox is good"),
        Suggestion(0, 3, "voltbox is worth it"),
        Suggestion(0, 4, "voltbox is waterproof"),
        Suggestion(0, 5, "voltbox is indian brand"),
        Suggestion(20, 2, "voltbox is overheating"),
    ),
    articles=(
        Article(
            0,
            "VoltBox launches Air 2 earbuds with 12-hour battery at Rs 2,999",
            "Tech Ledger",
            "https://techledger.example.com/voltbox-air-2-launch",
            good("A launch story."),
        ),
        Article(
            4,
            "VoltBox opens its first experience store in Bengaluru",
            "City Wire",
            "https://citywire.example.com/voltbox-store",
            good("Store opening.", Topic.CORPORATE),
        ),
        Article(
            9,
            "Festive sale: VoltBox Air 2 drops to Rs 2,499",
            "Deal Desk",
            "https://dealdesk.example.com/voltbox-air-2-sale",
            plain("A price cut.", Topic.PRICING),
        ),
        Article(
            19,
            "Users report VoltBox earbuds overheating while charging",
            "Gadget Ledger",
            "https://gadgetledger.example.com/news/voltbox-overheating",
            bad(80, "The press picks up the overheating reports."),
        ),
        Article(
            19,
            "VoltBox Air 2 owners share photos of swollen charging cases",
            "Tech Ledger",
            "https://techledger.example.com/voltbox-swollen-cases",
            bad(75, "Photos of the swelling cases in the press."),
        ),
        Article(
            20,
            "Consumer forum flags swelling VoltBox charging cases",
            "Consumer Watch Daily",
            "https://consumerwatch.example.com/news/voltbox",
            bad(85, "A consumer group flags the cases."),
        ),
        Article(
            20,
            "Should you stop charging your VoltBox earbuds? What we know",
            "Tech Ledger",
            "https://techledger.example.com/voltbox-what-we-know",
            bad(75, "The press tells owners to stop charging."),
        ),
        Article(
            20,
            "VoltBox case complaints triple in a week",
            "Gadget Ledger",
            "https://gadgetledger.example.com/news/voltbox-complaints",
            bad(80, "Complaints about the case grow fast."),
        ),
    ),
    reviews=(
        Review(
            0,
            5,
            "Pairing took seconds and the EQ presets are great.",
            good("Easy pairing.", Topic.APP_EXPERIENCE),
        ),
        Review(
            1,
            4,
            "Good app, the battery widget is handy. Wish it had a dark mode.",
            good("Likes the app.", Topic.APP_EXPERIENCE),
        ),
        Review(
            3,
            5,
            "Firmware update fixed the left bud dropping out.",
            good("An update fixed a problem.", Topic.APP_EXPERIENCE),
        ),
        Review(
            5,
            2,
            "Returned a faulty pair ten days ago and the refund still hasn't come.",
            bad(45, "A late refund.", REFUNDS, Topic.BILLING_REFUNDS),
        ),
        Review(
            6,
            4,
            "Find my earbuds saved me twice already.",
            good("A useful feature.", Topic.APP_EXPERIENCE),
        ),
        Review(
            8,
            3,
            "The app logs me out every week, otherwise fine.",
            Tag(-1, Topic.APP_EXPERIENCE, 20, "A small app annoyance."),
        ),
        Review(
            10,
            2,
            "Refund still pending after two weeks. Support just sends templates.",
            bad(50, "A refund that drags on.", REFUNDS, Topic.BILLING_REFUNDS),
        ),
        Review(11, 5, "Sound is excellent for the price.", good("Great sound for the money.")),
        Review(12, 4, "Comfortable for long calls, mic is decent.", good("Comfortable.")),
        Review(
            14,
            2,
            "The case gets warm while charging. Is that normal?",
            bad(50, "A case warming up while charging."),
        ),
        Review(
            16,
            1,
            "The charging case got really hot overnight and smelled like burning plastic.",
            bad(85, "The case overheated overnight."),
        ),
        Review(
            17,
            1,
            "Case is swelling and the lid won't close anymore. Scary.",
            bad(90, "A swollen case."),
        ),
        Review(
            18,
            2,
            "My case is hot to the touch after 30 minutes on the charger.",
            bad(60, "The case runs hot."),
        ),
        Review(
            19,
            1,
            "Stopped using it after the case scorched my desk.",
            bad(90, "The case scorched furniture."),
        ),
        Review(
            19,
            1,
            "Same overheating problem as everyone else. Support has no answer.",
            bad(80, "Overheating, with no help from support."),
        ),
        Review(
            19,
            1,
            "Battery swelling on a three week old case. I want a replacement now.",
            bad(85, "A new case swelled."),
        ),
        Review(
            20,
            1,
            "Case swelled up and cracked along the hinge.",
            bad(90, "A case cracked from swelling."),
        ),
        Review(
            20,
            1,
            "Charging it overnight is not safe. Don't buy until they fix this.",
            bad(85, "Warns others off the product."),
        ),
        Review(
            20,
            1,
            "Third report from my office alone. The case gets dangerously hot.",
            bad(85, "Several cases overheating."),
        ),
        Review(
            20,
            2,
            "Refund for my overheated unit is taking forever.",
            bad(60, "A refund for an overheated unit drags on.", REFUNDS, Topic.BILLING_REFUNDS),
        ),
    ),
    queries=(
        Query(0, "voltbox earbuds", False, plain("A search for the product.")),
        Query(0, "voltbox air 2", False, plain("A search for the product.")),
        Query(0, "voltbox charger", False, plain("A search for a product.")),
        Query(0, "voltbox air 2 price", True, plain("Interest in the price.", Topic.PRICING)),
        Query(0, "voltbox vs soundnest", True, plain("A comparison search.")),
        Query(19, "voltbox overheating", True, bad(70, "Searches about the case overheating.")),
        Query(20, "voltbox case swelling", True, bad(75, "Searches about swelling cases.")),
        Query(20, "voltbox charging case hot", True, bad(65, "Searches about a hot case.")),
        Query(20, "is voltbox safe", True, bad(70, "Searches doubting the product's safety.")),
    ),
    rating=((0, 4.4), (16, 4.3), (18, 4.1), (20, 3.8)),
)

MAIN = StoryBrand(
    "VoltBox",
    "voltbox",
    "com.example.voltbox",
    {
        "languages": ["en"],
        "search_page": {"templates": ["{brand}"], "pages": 1, "ai_overview": False},
        "autocomplete": {"prefixes": ["{brand} is "]},
        "news": {"extra_terms": []},
        "trends": {"related_queries": True},
        "play": {"review_sort": "newest", "review_pages": 1},
        "maps": OFF,
        "youtube": OFF,
    },
    1,
    timedelta(0),
    VOLTBOX,
)
